/**
 * TypeScript type definitions for the blog subsystem.
 * Based on data-model.md specification.
 */

/**
 * Represents a heading in the table of contents hierarchy.
 * Structure matches @stefanprobst/rehype-extract-toc output.
 */
export interface TOCEntry {
  /** Anchor ID (generated by rehype-slug) */
  id?: string;
  /** Heading text content */
  value: string;
  /** Heading depth (2 for h2, 3 for h3, etc.) */
  depth: number;
  /** Nested child headings */
  children?: TOCEntry[];
}

/**
 * Frontmatter type for MDX imports.
 * These fields are author-provided in the MDX file.
 */
export interface Frontmatter {
  /** Post title (required, max 200 characters) */
  title: string;
  /** ISO 8601 date (required, YYYY-MM-DD) */
  date: string;
  /** Author name for byline (required) */
  author: string;
  /** URL slug (optional, defaults to folder name) */
  slug?: string;
  /** Array of tag strings (optional) */
  tags?: string[];
  /** Short description (optional, auto-generated if omitted) */
  excerpt?: string;
}

/**
 * Reading time data computed by remark-reading-time.
 */
export interface ReadingTime {
  /** Minutes to read */
  minutes: number;
  /** Total word count */
  words: number;
}

/**
 * The primary content entity representing a blog article.
 */
export interface Post {
  // Required frontmatter (author-provided)
  /** Post title */
  title: string;
  /** ISO 8601 date */
  date: string;
  /** Author name for byline */
  author: string;

  // Optional frontmatter (author-provided)
  /** URL slug, defaults to folder name */
  slug: string;
  /** Array of tag strings */
  tags: string[];
  /** Short description */
  excerpt: string;

  // Computed at build time
  /** Minutes to read */
  readingTime: number;
  /** Total word count */
  wordCount: number;
  /** Table of contents structure */
  toc: TOCEntry[];
  /** Compiled MDX/HTML content */
  content: string;
}

/**
 * Aggregated tag metadata for the blog index.
 */
export interface Tag {
  /** Display name (original case from first usage) */
  name: string;
  /** URL-safe identifier (lowercase) */
  slug: string;
  /** Number of posts with this tag */
  count: number;
}

/**
 * Entry in the Fuse.js search index.
 */
export interface SearchIndexEntry {
  /** Post URL slug */
  slug: string;
  /** Post title (weighted high) */
  title: string;
  /** Post excerpt (weighted medium) */
  excerpt: string;
  /** Post tags (weighted medium) */
  tags: string[];
  /** Plain text content (weighted low) */
  content: string;
}

/**
 * Lightweight post metadata for listing pages.
 */
export interface PostCard {
  slug: string;
  title: string;
  date: string;
  author: string;
  excerpt: string;
  tags: string[];
  readingTime: number;
}

/**
 * MDX module augmentation for frontmatter/toc/readingTime exports.
 */
declare module "*.mdx" {
  import type { ComponentType } from "react";

  export const frontmatter: Frontmatter;
  export const toc: TOCEntry[];
  export const readingTime: ReadingTime;
  const MDXContent: ComponentType;
  export default MDXContent;
}
